### ISSUE TITLE
what would it take to use this from Java code?

### ISSUE THREAD

**Issue by gotson** [smithclay/lambdium#11]
the project looks very interesting !
I am not familiar with AWS Serverless Application Repo, but how complicated would it be to use this from a Lambda developed in Java with the Selenium WebDriver library ?

**Comment by smithclay** [comment]
Hi @gotson,

It would be slightly complicated, but not impossible (maybe several days to a week or two to get a prototype working?). You'd need to:

* Port the code in `index.js` to the Java equivalent. It basically is just a wrapper around a bundled binary that it calls (the webdriver and chrome browser instance). It's not complicated JavaScript but it'd help to be familiar with node.js conventions.
* Compile your existing Java selenium tests to work in the AWS Lambda environment and bundle with the function.

Depending on how many Java selenium tests you have or how familiar you are with AWS Lambda/node, it might be easier to rewrite your existing tests in Javascript.

The benefit of using a scripting language (python or node.js) to run tests in lambdium is that they don't have to be compiled beforehand. This allows people to specify the selenium script at runtime vs deploying them with the function.

**Comment by gotson** [comment]
Thanks for the details, i'll try to have a look !

Actually i'm not running tests, but using Selenium as part of an application. I need to interact with a website that doesn't provide API.
