### ISSUE TITLE
An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied

### ISSUE THREAD

**Issue by walrus95** [smithclay/lambdium#19]
I've run into trouble getting Lambdium running in my AWS environment. 

Following the directions on the README, I was able to run the _Visit Google_ scraper on my local machine, but ran into trouble when it came time to package the function for AWS:

```
$ sam package --template-file template.yaml --s3-bucket $LAMBDA_BUCKET_NAME --output-template-file packaged.yaml

Unable to upload artifact . referenced by CodeUri parameter of Lambdium resource.
An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```
Note that it was also necessary for me to install the AWS CLI:

```
$ sudo pip install awscli
$ aws configure
AWS Access Key ID [****************]: 
AWS Secret Access Key [****************]: 
Default region name [us-east-1]: 
Default output format [json]: 
```

I used my root credentials.

**Comment by smithclay** [comment]
You have to create an S3 bucket inside your own account and must set the `$LAMBDA_BUCKET_NAME`  to point to it.

1) create an S3 bucket in the AWS Console (can call it anything, note the name)
2) set the `LAMBDA_BUCKET_NAME` environment variable to point to that bucket:
3) `export LAMBDA_BUCKET_NAME=the-s3-bucket-inside-your-personal-account`
