### ISSUE TITLE
Key Input Not Supported

### ISSUE THREAD

**Issue by smithclay** [smithclay/lambdium#2]
When attempting to use key input, webdriver compains because the environment has no window system:

`
WebDriverError: unknown error: an X display is required for keycode conversions, consider using Xvfb_
`

Possible solutions:

1) Bundle Xvfb (gross)
2) Wait for ChromeDriver team to fix/open issue?

**Comment by ihavenoidea14** [comment]
Ever come up with a solution for this?

**Comment by smithclay** [comment]
Good news, looks like it was recently fixed in ChromeDriver 2.31:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1772#c28

Will try and fix the script in the next week that fetches the old version or so to point to the new release (and test it). Should be a simple update:
https://github.com/smithclay/lambdium/blob/master/scripts/fetch-dependencies.sh#L19

**Comment by ihavenoidea14** [comment]
Great news indeed! This is a very cool project.

**Comment by rbrtmrtn** [comment]
Sweet! Was this closed by 4f165219b72f203d1d103777b680dace441c0388?

**Comment by smithclay** [comment]
This has been addressed. New chromium and chromedriver are now bundled.
