### ISSUE TITLE
nodejs6.10 is no longer supported

### ISSUE THREAD

**Issue by moizfp** [smithclay/lambdium#27]
AWS has deprecated the Nodejs 6.10 environment so the SAM deployment fails.

Below is the error I am getting while deploying this Lamda.

`The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: df28c4c2-7c66-11e9-83ae-bf8662c2dcbc)`

**Comment by soterocra** [comment]
@moizfp any solution?

**Comment by moizfp** [comment]
Instead of using the SAM deployment on AWS. We can use the template provided in this git repo.
