### ISSUE TITLE
WebDriverError: unknown error: no chrome binary at /var/task/bin/headless_shell

### ISSUE THREAD

**Issue by chanson** [smithclay/lambdium#5]
Hi there! After following all the instructions (including using Terraform) and running the example script I get `WebDriverError: unknown error: no chrome binary at /var/task/bin/headless_shell` in the error log that gets sent back. Can you think of anything that might be causing this? 

Thanks, this is an awesome project!

**Comment by rbrtmrtn** [comment]
I also got the same. Hmm.

**Comment by smithclay** [comment]
Thanks for this! Looks like the URL changed.
