### ISSUE TITLE
serverless-chrome binaries

### ISSUE THREAD

**Issue by adieuadieu** [smithclay/lambdium#8]
Hi there — I noticed in `scripts/fetch-dependencies.sh` that this project is grabbing chrome binaries directly from the serverless-chrome repository:

https://github.com/smithclay/lambdium/blob/4f589cbb09ea152ec174fdb7b596ab296e516355/scripts/fetch-dependencies.sh#L15-L18

At some point soon, these binaries will be removed from the serverless-chrome repository as they're now quite old. Chrome binaries are now available under serverless-chrome's [releases](https://github.com/adieuadieu/serverless-chrome/releases) section. New binaries are automatically built and released whenever there's a new stable-channel version of Chromium/Chrome.

Would you be open to a PR which changes `scripts/fetch-dependencies.sh` to pull the binaries from serverless-chrome's releases? Are you aware of any issues with selenium webdriver that requires chrome v60 (which is what lambdium is currently fetching directly from the repository), or does the latest stable channel (v63) work, too?

**Comment by smithclay** [comment]
Absolutely open to a pull request—happy to pull directly from the new releases section. 

It should work with the latest stable channel (v63), just need to do some minor smoke testing first.

**Comment by smithclay** [comment]
Going to roll this into some refactoring the creation/install scripts, going to use SAM instead of terraform to get around the 50MB archive limit using the current process.
